In [1]:
import random

In [2]:
adj = [] 
for i in range(4):
    adj.append(random.sample(range(100),4))#The function selects four unique random numbers form the range 0 to 99
print(adj)

[[66, 63, 93, 29], [70, 72, 7, 18], [93, 50, 98, 37], [70, 83, 26, 3]]


In [3]:
for i in range(len(adj)):
    for j in range(len(adj[i])):
        if i == j: #Iterates over the elements of the list 'adj' and check if the row index == column index and set to 999
            adj[i][j] = 999
print(adj)

[[999, 63, 93, 29], [70, 999, 7, 18], [93, 50, 999, 37], [70, 83, 26, 999]]


In [4]:
import numpy as np
np.array(adj)

array([[999,  63,  93,  29],
       [ 70, 999,   7,  18],
       [ 93,  50, 999,  37],
       [ 70,  83,  26, 999]])

In [5]:
min(adj[0])

29

In [6]:
adj

[[999, 63, 93, 29], [70, 999, 7, 18], [93, 50, 999, 37], [70, 83, 26, 999]]

In [7]:
start = int(input()) #The input() function is used to read a line of text from the user's input.

0


In [8]:
visited = [] #empty list to keep track of visited nodes
dist = 0 #distance variable to 0
visited.append(start) #Add the start node to visited list
while list(set(visited)) != [i for i in range(len(adj))]: #continue the loop until all nodes have been visited
    for i in range(len(adj)): #Iterates over the indices of the 'adj' matrix
        adj[i][visited[-1]] = 999 #set the value of the current node in the 'adj' matrix to 999. This marks the node as visited by making its distance from any other node effectively infinite
    nxt = adj[visited[-1]].index(min(adj[visited[-1]]))#Find the index of the next node to visit by getting the index of the minimum value in the row
    dist += min(adj[visited[-1]]) #Add the mininum value in the row of the last visited node to the 'dist' variable incrementing the distance travelled.
    print(np.array(adj)) #print the current state of the 'adj' matrix
    print(nxt) #print the index of the next node to be visited
    visited.append(nxt) #Add the node to the 'visited' list
    continue

[[999  63  93  29]
 [999 999   7  18]
 [999  50 999  37]
 [999  83  26 999]]
3
[[999  63  93 999]
 [999 999   7 999]
 [999  50 999 999]
 [999  83  26 999]]
2
[[999  63 999 999]
 [999 999 999 999]
 [999  50 999 999]
 [999  83 999 999]]
1


In [9]:
dist

105

In [10]:
visited

[0, 3, 2, 1]